package org.group1.coffeeshopapi.common.enums;

public enum OrderAuditAction {
    CREATED, CASH_COLLECTED, BAKONG_CONFIRMED, BAKONG_BY_RECEIPT, CANCELLED, DELIVERY_FEE_SET, ESTIMATE_SET,
    CASH_SELECTED, BAKONG_QR_GENERATED,
    LOCATION_PINNED,
    STAFF_CALLED, STAFF_CALL_ANSWERED,
    PREPARING, OUT_FOR_DELIVERY, DELIVERED, COMPLETED
}
