-- The general/manual "business expense" feature (rent, wages, Excel import, admin CRUD, staff
-- attribution via recorded_by) has been removed entirely. Expense tracking is now stock-purchase
-- only, via the "stock_expenses" table (auto-generated by InventoryServiceImpl on every stock-in,
-- no manual entry, no staff/attendant column). ddl-auto: update never drops a table it no longer
-- manages, so the old table has to be dropped by hand.
--
-- DESTRUCTIVE: this permanently deletes all rent/wages/utilities/... expense history — export it
-- first if that data still matters. Covers every name this table has had during development
-- ("expenses" originally; briefly "operational_expenses" / "business_expenses" in intermediate
-- iterations of this feature) so it's safe to run once against any database regardless of which
-- name it's currently under, and safe to run more than once (each DROP is IF EXISTS).
-- Run against every database that has one of these tables: local dev DB and production.

DROP TABLE IF EXISTS expenses;
DROP TABLE IF EXISTS operational_expenses;
DROP TABLE IF EXISTS business_expenses;
