ALTER TABLE auth_users DROP COLUMN IF EXISTS full_name;
ALTER TABLE auth_users DROP COLUMN IF EXISTS email;
ALTER TABLE auth_users DROP COLUMN IF EXISTS password;
ALTER TABLE auth_users DROP COLUMN IF EXISTS phone_number;
ALTER TABLE auth_users DROP COLUMN IF EXISTS gender;
ALTER TABLE auth_users DROP COLUMN IF EXISTS status;
ALTER TABLE auth_users DROP COLUMN IF EXISTS telegram_chat_id;
ALTER TABLE auth_users DROP COLUMN IF EXISTS created_at;
ALTER TABLE auth_users DROP COLUMN IF EXISTS updated_at;